# Run with --renew-anon-volumes
# -- build for newzcraper

version: '3.1'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${ROOT}"
      MONGO_INITDB_ROOT_PASSWORD: "${PASSWORD}"
    ports:
      - "27017:27017"
    networks:
      - newzcraper
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${ROOT}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${PASSWORD}"
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - newzcraper
  newzcraper:
    build: newzcraper
    container_name: newzcraper
    depends_on:
      - mongo
    environment:
      PYTHONUNBUFFERED: 1
      MONGO_ADMINUSERNAME: "${ROOT}"
      MONGO_ADMINPASSWORD: "${PASSWORD}"
      DB_NAME: "${DB_NAME}"
      COLLECTION_NAME: "${COLLECTION_NAME}"
    volumes:
      - ./newzcraper:/app
    networks:
      - newzcraper
  flask:
    build: flask
    container_name: flask
    depends_on:
      - mongo
    environment:
      PYTHONUNBUFFERED: 1
      MONGO_ADMINUSERNAME: "${ROOT}"
      MONGO_ADMINPASSWORD: "${PASSWORD}"
      DB_NAME: "${DB_NAME}"
      COLLECTION_NAME: "${COLLECTION_NAME}"
    ports:
      - "5000:5000"
    volumes:
      - ./flask:/app
    networks:
      - newzcraper
networks:
    newzcraper:
        name: newzcraper
