# Run with --renew-anon-volumes
# -- build for newzcraper

version: '3.1'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - newzcraper
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - newzcraper
  newzcraper:
    build: .
    container_name: newzcraper
    depends_on:
      - mongo
    environment:
      PYTHONUNBUFFERED: 1
      MONGO_ADMINUSERNAME: root
      MONGO_ADMINPASSWORD: example
    volumes:
      - ./newzcraper:/app/newzcraper
    networks:
      - newzcraper
networks:
    newzcraper:
        name: newzcraper
